from OpenGL.GL import *

def draw_simple_cube(size=1.0):
    half = size / 2
    glBegin(GL_QUADS)
    # Ön
    glVertex3f(-half, -half, half)
    glVertex3f(half, -half, half)
    glVertex3f(half, half, half)
    glVertex3f(-half, half, half)
    # Arka
    glVertex3f(-half, -half, -half)
    glVertex3f(half, -half, -half)
    glVertex3f(half, half, -half)
    glVertex3f(-half, half, -half)
    # Sol
    glVertex3f(-half, -half, -half)
    glVertex3f(-half, -half, half)
    glVertex3f(-half, half, half)
    glVertex3f(-half, half, -half)
    # Sağ
    glVertex3f(half, -half, -half)
    glVertex3f(half, -half, half)
    glVertex3f(half, half, half)
    glVertex3f(half, half, -half)
    # Üst
    glVertex3f(-half, half, -half)
    glVertex3f(half, half, -half)
    glVertex3f(half, half, half)
    glVertex3f(-half, half, half)
    # Alt
    glVertex3f(-half, -half, -half)
    glVertex3f(half, -half, -half)
    glVertex3f(half, -half, half)
    glVertex3f(-half, -half, half)
    glEnd()

def draw_textured_cube(top_tex, side_tex, size=1.0):
    half = size / 2
    glEnable(GL_TEXTURE_2D)
    glBindTexture(GL_TEXTURE_2D, top_tex[0] if isinstance(top_tex, tuple) else top_tex)
    glBegin(GL_QUADS)
    glColor3f(1.0, 1.0, 1.0)
    glTexCoord2f(0, 0); glVertex3f(-half, half, -half)
    glTexCoord2f(1, 0); glVertex3f(half, half, -half)
    glTexCoord2f(1, 1); glVertex3f(half, half, half)
    glTexCoord2f(0, 1); glVertex3f(-half, half, half)
    glEnd()
    glBindTexture(GL_TEXTURE_2D, side_tex[0] if isinstance(side_tex, tuple) else side_tex)
    glBegin(GL_QUADS)
    glColor3f(1.0, 1.0, 1.0)
    glTexCoord2f(0, 0); glVertex3f(-half, -half, -half)
    glTexCoord2f(1, 0); glVertex3f(half, -half, -half)
    glTexCoord2f(1, 1); glVertex3f(half, -half, half)
    glTexCoord2f(0, 1); glVertex3f(-half, -half, half)
    glEnd()
    glBegin(GL_QUADS)
    glTexCoord2f(0, 0); glVertex3f(-half, -half, half)
    glTexCoord2f(1, 0); glVertex3f(half, -half, half)
    glTexCoord2f(1, 1); glVertex3f(half, half, half)
    glTexCoord2f(0, 1); glVertex3f(-half, half, half)
    glEnd()
    glBegin(GL_QUADS)
    glTexCoord2f(0, 0); glVertex3f(-half, -half, -half)
    glTexCoord2f(1, 0); glVertex3f(half, -half, -half)
    glTexCoord2f(1, 1); glVertex3f(half, half, -half)
    glTexCoord2f(0, 1); glVertex3f(-half, half, -half)
    glEnd()
    glBegin(GL_QUADS)
    glTexCoord2f(0, 0); glVertex3f(-half, -half, -half)
    glTexCoord2f(1, 0); glVertex3f(-half, -half, half)
    glTexCoord2f(1, 1); glVertex3f(-half, half, half)
    glTexCoord2f(0, 1); glVertex3f(-half, half, -half)
    glEnd()
    glBegin(GL_QUADS)
    glTexCoord2f(0, 0); glVertex3f(half, -half, -half)
    glTexCoord2f(1, 0); glVertex3f(half, -half, half)
    glTexCoord2f(1, 1); glVertex3f(half, half, half)
    glTexCoord2f(0, 1); glVertex3f(half, half, -half)
    glEnd()
    glDisable(GL_TEXTURE_2D) 