from OpenGL.GL import *

def draw_skybox(sky_tex, size=100.0):
    half = size / 2
    glPushMatrix()
    glDisable(GL_DEPTH_TEST)
    glEnable(GL_TEXTURE_2D)
    glBindTexture(GL_TEXTURE_2D, sky_tex)
    glColor3f(1.0, 1.0, 1.0)
    glBegin(GL_QUADS)
    glTexCoord2f(0, 0); glVertex3f(-half, -half, -half)
    glTexCoord2f(1, 0); glVertex3f(half, -half, -half)
    glTexCoord2f(1, 1); glVertex3f(half, half, -half)
    glTexCoord2f(0, 1); glVertex3f(-half, half, -half)
    glTexCoord2f(0, 0); glVertex3f(-half, -half, half)
    glTexCoord2f(1, 0); glVertex3f(half, -half, half)
    glTexCoord2f(1, 1); glVertex3f(half, half, half)
    glTexCoord2f(0, 1); glVertex3f(-half, half, half)
    glTexCoord2f(0, 0); glVertex3f(-half, half, -half)
    glTexCoord2f(1, 0); glVertex3f(half, half, -half)
    glTexCoord2f(1, 1); glVertex3f(half, half, half)
    glTexCoord2f(0, 1); glVertex3f(-half, half, half)
    glTexCoord2f(0, 0); glVertex3f(-half, -half, -half)
    glTexCoord2f(1, 0); glVertex3f(half, -half, -half)
    glTexCoord2f(1, 1); glVertex3f(half, -half, half)
    glTexCoord2f(0, 1); glVertex3f(-half, -half, half)
    glTexCoord2f(0, 0); glVertex3f(-half, -half, -half)
    glTexCoord2f(1, 0); glVertex3f(-half, -half, half)
    glTexCoord2f(1, 1); glVertex3f(-half, half, half)
    glTexCoord2f(0, 1); glVertex3f(-half, half, -half)
    glTexCoord2f(0, 0); glVertex3f(half, -half, -half)
    glTexCoord2f(1, 0); glVertex3f(half, -half, half)
    glTexCoord2f(1, 1); glVertex3f(half, half, half)
    glTexCoord2f(0, 1); glVertex3f(half, half, -half)
    glEnd()
    glEnable(GL_DEPTH_TEST)
    glDisable(GL_TEXTURE_2D)
    glPopMatrix() 